language: node_js
node_js:
    - stable
deploy:
    provider: npm
    email: arsovik@gmail.com
    api_key:
        secure: WmbsXJj/s8ibfEy562Bf1q5e7GhyFnXut+Uu4bYwxoh0KdhW2QI2mg++4QOyy+66KONYQG71Q/QcCa3yMqGXvmuCoOlX44A1RjvvCW6YGeLoYMySMLdfFGPo4b+wyPIZblb3F7qPBpNPIbDpbwk3So8EBIm+tLxp+auarXYcyZbI3X/tJp0nC8aAGQrVCuvtJrYJ0jVtGB7+yYgCfL19ikNWnAtZzR6agd0/eFxd6qVEvBYRMZRVMF+eygkMye7oUxT9gYj71eZ/9C1mrfgHqcj9jQowA/6STa+GuYUwjIVWBaOT321OlIZ0TvYIfMirYZHe/CKVXDGTZz29uW/tv9Nmr02ZI/9xTlxTyIzS3Kym0XTMExDwvBYvU4yY+BDTV8yjwrVA+LMyCLroHnHyb6sv9u13IJlJaziNgVuvpB0AR4llGtvQr6ldeJums3kZXZPhQ0pueJ4KaLGAW34kCQzHLaaJs6m57dvhjLJ4TJjfsA01ZJvo9so89q+sk6qjCav/XxxHwirYdOzSCKHhZ886ZOuKNiQirYrTC+CvN/HSeGXyqymGa7nnmCt37vXvWmB7F2MAkhKPJcWizRKG8cwwR1PRtHJWZ7nJD5mK8ZSdliLc2aUFMjL0jQ2L95FdkULnBvd0wDTc7ZmCCd9FRSfjg3+gslBsMOf12gz7SuM=
    on:
        tags: true
addons:
    code_climate:
        repo_token:
            secure: VAPgCV/BAOZyzWFvPdOO8pzD796+5M8BnGXFWPMwqSnhLPGZFJdUiCFnIRC6yV1tQTig05X5aYw8cYlpJZdTzp68vAae8x2Kd2PA4DG+fc06UTj+p5f8X5hCiMXIJGhV7adLm4rYIkxKgJKYn9yWcU3vvg61k46sTwBBohqRzdP8qS4jOR2ttNz38WLWY7jlQzOFRgcVxMaZbj6L7LIiUCJJqUxIoxy2WY9EPJ5tEjgiRr5xKHYnSbphl4qmSPHU0k1aa/d5zvO999Kxn1q+5O+NQc8OvsC9azE3blqlsCtIC2b0TuvwFoLpAtMecp7vPpICTYgBLq8mRBdWkHBlCrnavUYq0GD9JGUXFeOyeWnx8tfs3ILNpVrqHLl/mLOmVy2FJX47+64WQ6dB9HBmsYglFEHvnaQQ8I4ZUTvbwzN5li1yNHw145PsyGxfNyrNxNMWpsDrv51NQUPxt3YO2ipEhVggV92dL1MZyVWm0JYLZUCmIp0nUM9yC5cPrpQcQbuJJOkn3NxMc75pm7i3dk6+Vaa+vr+LuazvtD2P1Wkbh0m4cETbXwvuWUS7RsTQNWJTLj9NDknASpToTJYp28E/4eihiM1Fg1VE51iNOUpoRJtYKbXJ53ujCQoVdXJYufGFYAok7jCwOUQOWpJHNsp/WlSYhtx9psC6XH4YGxU=
after_script:
    - codeclimate-test-reporter < coverage/lcov.info
    - cat coverage/lcov.info | node_modules/.bin/coveralls
