language: node_js
node_js:
    - stable
deploy:
    provider: npm
    email: arsovik@gmail.com
    api_key:
        secure: WmbsXJj/s8ibfEy562Bf1q5e7GhyFnXut+Uu4bYwxoh0KdhW2QI2mg++4QOyy+66KONYQG71Q/QcCa3yMqGXvmuCoOlX44A1RjvvCW6YGeLoYMySMLdfFGPo4b+wyPIZblb3F7qPBpNPIbDpbwk3So8EBIm+tLxp+auarXYcyZbI3X/tJp0nC8aAGQrVCuvtJrYJ0jVtGB7+yYgCfL19ikNWnAtZzR6agd0/eFxd6qVEvBYRMZRVMF+eygkMye7oUxT9gYj71eZ/9C1mrfgHqcj9jQowA/6STa+GuYUwjIVWBaOT321OlIZ0TvYIfMirYZHe/CKVXDGTZz29uW/tv9Nmr02ZI/9xTlxTyIzS3Kym0XTMExDwvBYvU4yY+BDTV8yjwrVA+LMyCLroHnHyb6sv9u13IJlJaziNgVuvpB0AR4llGtvQr6ldeJums3kZXZPhQ0pueJ4KaLGAW34kCQzHLaaJs6m57dvhjLJ4TJjfsA01ZJvo9so89q+sk6qjCav/XxxHwirYdOzSCKHhZ886ZOuKNiQirYrTC+CvN/HSeGXyqymGa7nnmCt37vXvWmB7F2MAkhKPJcWizRKG8cwwR1PRtHJWZ7nJD5mK8ZSdliLc2aUFMjL0jQ2L95FdkULnBvd0wDTc7ZmCCd9FRSfjg3+gslBsMOf12gz7SuM=
    on:
        tags: true
addons:
    code_climate:
        repo_token:
            secure: pWKW7ckfZSCbsSdozJUlfqDHlXNRvsi142z6yVmaNTmfPNkTSSsgd/gaKs2oXSE4A25cY5ukl5Au/pSkFIKEty0BcmHvTHHf0Oe1R72vPGAnmcWgj1rB8Pb6xCwFd/nJdXFRy7UdCK4r7GKcwd6nvfR7yTQOLBTMk5s75K63oUd8buKbdfV8Bjx+8o3v/5Y5N1LGty6uyncXZ3x4Ik1+63yqDAFzNzFn9z+9RxY7RZqg5j2X+8x5aOKtPcynVJOwv8OSAa8iKEZmBGp70UqYd2GgMBRLVSflpuRRYwrVGXy5aNM/vU7m4rbyEWrsICc2fUtSsQgri8KmmMGCTQ81MOGa/th8yN0mzQw+ztDuVKoiHvpn0fMLQrbp5ikOzS6sTwRRi+n0nWt91Mewqdd019881Eova7rmm+0NSxBzYJKBP2ibW/XN4lORX7V7YVVo5EKNA0t+ke5ZebSQxzEvvxLpRwCoJG9eaUCYtpuBM+jJW/6lvXtEReBSRMJiPyE+m4czZUqRF+/8LPIs7FCZq8PjMs2myNlnZKJ3sw2aTqYr4mqHOY09BXrHImrqsGZ5Nruhcvcble46tzcjy16jwAzei25jiFQdFLPS7mcscQDvHR6AtkeL9Yyf/NmEkZh/Lfd83v3y20kTMF23YrQwuV6owOl4L3ZdgQwbwYk63qY=
after_script:
    - codeclimate-test-reporter < coverage/lcov.info
    - cat coverage/lcov.info | node_modules/.bin/coveralls
