language: node_js
node_js:
    - stable
deploy:
    provider: npm
    email: arsovik@gmail.com
    api_key:
        secure: WmbsXJj/s8ibfEy562Bf1q5e7GhyFnXut+Uu4bYwxoh0KdhW2QI2mg++4QOyy+66KONYQG71Q/QcCa3yMqGXvmuCoOlX44A1RjvvCW6YGeLoYMySMLdfFGPo4b+wyPIZblb3F7qPBpNPIbDpbwk3So8EBIm+tLxp+auarXYcyZbI3X/tJp0nC8aAGQrVCuvtJrYJ0jVtGB7+yYgCfL19ikNWnAtZzR6agd0/eFxd6qVEvBYRMZRVMF+eygkMye7oUxT9gYj71eZ/9C1mrfgHqcj9jQowA/6STa+GuYUwjIVWBaOT321OlIZ0TvYIfMirYZHe/CKVXDGTZz29uW/tv9Nmr02ZI/9xTlxTyIzS3Kym0XTMExDwvBYvU4yY+BDTV8yjwrVA+LMyCLroHnHyb6sv9u13IJlJaziNgVuvpB0AR4llGtvQr6ldeJums3kZXZPhQ0pueJ4KaLGAW34kCQzHLaaJs6m57dvhjLJ4TJjfsA01ZJvo9so89q+sk6qjCav/XxxHwirYdOzSCKHhZ886ZOuKNiQirYrTC+CvN/HSeGXyqymGa7nnmCt37vXvWmB7F2MAkhKPJcWizRKG8cwwR1PRtHJWZ7nJD5mK8ZSdliLc2aUFMjL0jQ2L95FdkULnBvd0wDTc7ZmCCd9FRSfjg3+gslBsMOf12gz7SuM=
    on:
        tags: true
addons:
    code_climate:
        repo_token:
            secure: WcfRWj8LJkM791xnPT1wlXCAB2EBzwqA8qtj+jlFRfO2LDQRbbW3odMyigo3yvdKkRgInEPT9uEaK8opTw/ciG2UCkf1HefXz2aURyvF9MFGHK/atMq69OMVxhB6TqXcBVl97eJdREdichJZk1cFe+MIy6WKvpieJzTZviHbCnN0xtZsY1WuPGUdx4auQGh82ZIYz7rvSPupc/bOEbf9kHnwLVbHuwoKDtK3RdgWTpq0FJ1lZVQYB0Mv2LpQ+kSLZgpUcgTh9jOb1BvrEprkhEIP9MAoNcTd0xShyZZRTuOmS9ymXSZLml4PYaxJF5IdS59RIx5DJ3xBLjk0DiBIC4yxlYGz/y6REI/2/SVhYPhy6cNZjlj0Awno8YlTGJOdGwfer2B/I9AJEo+ih2osIuw7ahXlWVj59DawogLNhYj15LEdLhBLvRKT+eV58YPP6VOm3Q4zGSqnb4oW/4OPivbMxSnnVj1Qnhbqu7fNNSI85mPfbDHWWDLHbIS3aPVNATuRlzj0DrZL/zXetVkP3M9Qw1JvvI+zNM+In180tafpZWhM2rJRovw5pX5+7Ww7qi9QErDMwvtraO6c6ouJr8SoZ//k2AnamNo65zSwKNMc0hoAZbXC3fS/XuqqnC0GVVtk7zIN/rAh276FS8DRJ2W3vr7Fxy2U5uGBfTsxo1M=
after_script:
    - codeclimate-test-reporter < coverage/lcov.info
    - cat coverage/lcov.info | node_modules/.bin/coveralls
