language: node_js
node_js:
    - stable
deploy:
    provider: npm
    email: arsovik@gmail.com
    api_key:
        secure: 1w51I/egCnymWolfZMLQQG05jrEwBYzJ0ysFgU+qZ9Ygmk0+hbHhd9tdxPOZDF+ORB/XWnoJKjmdt2PIPreDp6ErFHO1BumndMghMqMROKkfIQ8jV1IAjS9GhDNy19yJQ/cqgpO+8PkTOUwTFg+PlqmcG8BOMJJrvzwE1vcqpbEUxc63KSoSuZKjKrVXy4cc+Vx72IwkYFWZH/o8OYCzw0hBXJQJH4Kr8N70pTdNJpdhUwgNu1OEHeVt6WrJk58N+JwBDKt6YY2cEM6LL4zw6c1bzUjCevrp9g0CGiiz3QYLA8RXDekeDBsX7tXkwKdX10CGxNRKqGlmCYQRQuGfBsSwB6fv7xZR2ly1D/qIgRk7jx8MDDHUWbyaQcXRaOOzf2ZutC996DjYBQFGjJMgNwEff0yct80r0j2KpzmwHDDcT1asNJtDzVispQEXzkVjQdSzjFR0JxUeci4j04ylARS1/4/yA4CpDJ1wR5UYD4Gd2nh+nDtMIleBpi49ltZySWvoV9eoOs7ZSuy3e3l3PnD4oIkEILW79FfbZi9icWz7pwcI8sUyT+ORNjxommodDuOQSGDTSuUSkng1eiKte61co7R4+Npl/RQUo0atkSr+FroOooDY3aTsVFnuCyBPdlsWI/aJvtlRyLsiHvrqwcXElaadqQJEKcwY2wjN2wk=
    on:
        tags: true
addons:
    code_climate:
        repo_token:
            secure: TNT2R+Mg0H+TJ5NMs6oiGgOqcPeqqE2a6r29U+LSbegRjiXrMCbVLjcNQUxoXy0CYrm77tToi7BXqazWRoKv5jSyPk2qAE0RUUwMYetMGKqIA+XIg/ZFaApvXkbBXRr0/CBfLdwnEYlxaVYHh4eN7qWNuPc6rTb5Yh+EBSnwh/Hs1hKTVrYf+kQhA+udDE2CApcK0dHgAV8j18lW57NFhz2J5Bn3g9DUdryaMFQkgQGy60qfJnWdrKnphRLJtAxDIzrHBarjWsbJkofeUfrzPzkt1DeDj/3qtJZLFiOhltNBa+HEnEUsqOC3dSxC/hDpxGLGC02zkqMeKgNp4XuwVCwJQ3VR4JUQ3II96PUJIBKrjAMD8YI6NPLRxO8pFzyHbqIc0WJRU3d+9FKLTjQ7BuzuJapoCd0yzq/9V5daHSe/9+iGw69jE2Atl1vBk4HQC24aPOGqnzwcbc3u66HNG14BcF0mDFZXWsAxXHpkMKWDR0PDxo4oZBP9dYtO0sVu4GBjVDkqmxNyamQi7M0wSpLWZCqRWyHqJs8pS4hl5aTQWgKW51+8CnH4EPhGzhFepWrUdXTYD8Zf9UIKv4m97G+kEncOW9X8OuNo6bgQ09siMS/P6GOiM/ZqDAJGqQTbcW5Ot363zOQAY64okvvvJKO+ucMddRz5iRMTMhXFi2k=
after_script:
    - codeclimate-test-reporter < coverage/lcov.info
    - cat coverage/lcov.info | node_modules/.bin/coveralls
