branches:
  only:
  - master
language: node_js
node_js:
    - stable
addons:
    code_climate:
        repo_token:
            secure: VAPgCV/BAOZyzWFvPdOO8pzD796+5M8BnGXFWPMwqSnhLPGZFJdUiCFnIRC6yV1tQTig05X5aYw8cYlpJZdTzp68vAae8x2Kd2PA4DG+fc06UTj+p5f8X5hCiMXIJGhV7adLm4rYIkxKgJKYn9yWcU3vvg61k46sTwBBohqRzdP8qS4jOR2ttNz38WLWY7jlQzOFRgcVxMaZbj6L7LIiUCJJqUxIoxy2WY9EPJ5tEjgiRr5xKHYnSbphl4qmSPHU0k1aa/d5zvO999Kxn1q+5O+NQc8OvsC9azE3blqlsCtIC2b0TuvwFoLpAtMecp7vPpICTYgBLq8mRBdWkHBlCrnavUYq0GD9JGUXFeOyeWnx8tfs3ILNpVrqHLl/mLOmVy2FJX47+64WQ6dB9HBmsYglFEHvnaQQ8I4ZUTvbwzN5li1yNHw145PsyGxfNyrNxNMWpsDrv51NQUPxt3YO2ipEhVggV92dL1MZyVWm0JYLZUCmIp0nUM9yC5cPrpQcQbuJJOkn3NxMc75pm7i3dk6+Vaa+vr+LuazvtD2P1Wkbh0m4cETbXwvuWUS7RsTQNWJTLj9NDknASpToTJYp28E/4eihiM1Fg1VE51iNOUpoRJtYKbXJ53ujCQoVdXJYufGFYAok7jCwOUQOWpJHNsp/WlSYhtx9psC6XH4YGxU=
after_script:
    - codeclimate-test-reporter < coverage/lcov.info
    - cat coverage/lcov.info | node_modules/.bin/coveralls
